all:
	gcc -O3 -Werror -o hw0401 hw0401.c
	gcc -O3 -Werror -o hw0402 hw0402.c
	gcc -O3 -Werror -o hw0403 hw0403.c
	gcc -O3 -Werror -o hw0404 hw0404.c

clean:
	rm -rf hw0401 hw0402 hw0403 hw0404

first:
	./hw0401 --count 10 --timestamp --interval 2

second:
	./hw0402

third:
	./hw0403

fourth:
	./hw0404