all:
	gcc -O3 -std=c17 -Wall -Werror -o hw0101 hw0101.c
	gcc -O3 -std=c17 -Wall -Werror -o hw0102 hw0102.c
	gcc -O3 -std=c17 -Wall -Werror -o hw0103 hw0103.c
	gcc -O3 -std=c17 -Wall -Werror -o hw0104 hw0104.c

clean:
	rm -rf hw0101 hw0102 hw0103 hw0104