all:
	gcc -O3 -Werror hw0301.c -o hw0301
	gcc -O3 -Werror hw0302.c -o hw0302
	gcc -O3 -Werror hw0303.c -o hw0303
	gcc -O3 -Werror hw0304.c cheat.c -o hw0304
	gcc -O3 -Werror hw0305.c -o hw0305

clean:
	rm -rf hw0301 hw0302 hw0303 hw0304 hw0305

first:
	./hw0301 -e -k key -i output -o output

second:
	./hw0302 -d test.zip

third:
	./hw0303 -x 500 -y 800 -w 400 -h 350 -n 30 -i 1.bmp

fourth:
	./hw0304

fifth:
	./hw0305