all:
	gcc -O3 -Werror hw0301.c -o hw0301
	#gcc -O3 -Werror hw0302.c -o hw0302
	gcc -O3 -Werror hw0303.c -o hw0303

clean:
	rm -rf hw0301 hw0302 hw0303

first:
	./hw0301 -e -k key -i output -o output

second:
	./hw0302 -d

third:
	./hw0303 -x 500 -y 800 -w 400 -h 350 -n 30 -i 1.bmp